config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  root 'companies#index'

  get '#' =>        'companies#guess'
  post 'company' => 'companies#return'

  get 'login' =>    'sessions#new'
  post 'login' =>   'sessions#create'
  delete 'login' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
require 'pry'

class Company < ActiveRecord::Base
  validates_uniqueness_of :company_number
  validates_presence_of :name, :company_number, :company_type, :incorporation_date, :registered_address, :current_status

  has_many :officer

  attr_reader :companies, :name, :company_number, :company_type, :incorporation_date, :registered_address_in_full, :current_status, :jurisdiction_code

  def initialize(searched_company)
    @search = searched_company
    load
  end

  def load
    binding.pry
    @clean_company = @search.downcase.gsub(/\s+/, "+")
    search_company
  end

  def search_company
    if @clean_company.length >= 2
      @data = get_json("https://api.opencorporates.com/companies/search?q=#{@clean_company}")
      unless @data['results']['companies'].empty?
        parse_search_results
        @companies = Company.all
      end
    end
  end

  def parse_search_results
    a = 0
    
    until @data['results']['companies'][a].nil?
      binding.pry
      @name = @data['results']['companies'][a]['company']['name']
      @company_number = @data['results']['companies'][a]['company']['company_number']
      @company_type = @data['results']['companies'][a]['company']['company_type']
      @incorporation_date = @data['results']['companies'][a]['company']['incorporation_date']
      @registered_address_in_full = @data['results']['companies'][a]['company']['registered_address_in_full']
      @current_status = @data['results']['companies'][a]['company']['current_status']
      @jurisdiction_code = @data['results']['companies'][a]['company']['jurisdiction_code']
      register_company
      a += 1
    end

  end

  def register_company
    @company = Company.create!(
      name: @name,
      company_number: @company_number,
      company_type: @company_type,
      incorporation_date: @incorporation_date,
      registered_address_in_full: @registered_address_in_full,
      current_status: @current_status,
      jurisdiction_code: @jurisdiction_code
    )
  end

  def get_json(url)
    HTTParty.get(url).parsed_response
  end
end

app/models/officer.rb
class Officer < ActiveRecord::Base
  validates_uniqueness_of :officer_id
  validates_presence_of :name, :companies_id, :officer_id, :position, :start_date

  belongs_to :company
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :username, :password_digest, :email
  validates :username, uniqueness: true, length: { in: 3..16 }
  validates :password_digest, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :require_user, only: [:index, :show]

  def index
    @user = User.find(session[:user_id])
  end

  def guess
  end

  def return
    @searched_company = Company.new(params['company']['company'])

    if !@data.nil?
      @company = Company.create!(
        name: @name,
        company_number: @company_number,
        company_type: @company_type,
        incorporation_date: @incorporation_date,
        registered_address_in_full: @registered_address_in_full,
        current_status: @current_status,
        jurisdiction_code: @jurisdiction_code
      )
      @companies = Company.all
      return @companies
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/#'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session.clear
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/#'
    else
      redirect_to '/login'
    end
  end

  # def profile
  #   @user = User.find(session[:user_id])
  #   @saves =
  # end

  # def edit
  #   @user = User.find(session[:user_id])
  #   @user.username = params[:user][:username]
  #   @user.save
  #   redirect_to '/profile'
  # end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.haml
.container.container-all
  %h1.first-header Search through over 110,000,000 companies:
  .container.container-search
    = form_for :company, url: {action: "return"} do |f|
      = f.text_field :company, :placeholder => "Company name"
      = f.submit "Enter"

app/views/companies/return.html.haml
.container.container-all
  %h1.first-header Search through over 110,000,000 companies:
  .container.container-search
    = form_for :company, url: {action: "return"} do |f|
      = f.text_field :company, :placeholder => "Company name"
      = f.submit "Enter"
  .container.container-answer
    - if @companies.nil?
      %h2 No company matches this search result.  Try again.
    -else
      %ul.companies
        - @companies.each do |company|
          %li.entry
            %i.business-entry
            %h2 #{company.name}
            %h3 Company Number: #{company.company_number}
            %h3 Company Type: #{company.company_type}
            %h3 Incorporation Date: #{company.incorporation_date}
            %h3 Registered Address: #{company.registered_address_in_full}
            %h3 Current Status: #{company.current_status}
            %h3 Jurisdiction Code: #{company.jurisdiction_code}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans", :rel => "stylesheet"}/
    %title Predictive Ops
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
    - if current_user
      %ul.user-prompts
        %p= link_to "#{current_user.username}", 'profile'
        %p= link_to "Game", 'game'
        %p= link_to "Leaderboard", 'leaderboard'
        %p= link_to "Log Out", login_path, method: "delete"
    - else
      %ul.user-prompts
    .container
      = yield